# Generated by Django 4.1.6 on 2023-03-09 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empid', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('dept', models.CharField(max_length=100)),
                ('doj', models.CharField(max_length=100)),
                ('dob', models.CharField(max_length=100)),
                ('empphoto', models.FileField(upload_to='empphoto')),
            ],
        ),
    ]
